### ISSUE TITLE
Implement EndingStack Stored Procedure

### ISSUE THREAD

**Issue by tompuglisi** [tompuglisi/PokerViewer#6]
We need to write the stored procedure to populate the EndingStack column

**Comment by cotterrm** [comment]
Nothing in the criteria mentions that we need to do this, but we should do this to be safe

**Comment by cotterrm** [comment]
Running UpdateEndingStack.sql on the database will implement the stored procedure. It can then be enacted by the command "call UpdateEndStack;"
