### ISSUE TITLE
Table ID and player names can contain "/"

### ISSUE THREAD

**Issue by tompuglisi** [tompuglisi/PokerViewer#8]
We need to generate unique numeric IDs for tables and players when they're entered into the database. The details views are currently resulting in invalid URLs because of this.

**Comment by cotterrm** [comment]
Couple different options on how to solve this:

Parse names before we put it into the database and strip/replace characters.

Give these tables an ID that is numeric and autogenerated

create a function to auto generate a non garbage ID

**Comment by tompuglisi** [comment]
When using MySQL's auto-generation functionality for PlayerID and TableID, I need to call db.SaveChanges() every time I add a player to the database in order to get the generated ID. This might make parsing even slower.

The other option I'd like to use is to generate IDs with our own generation method. I'd like to just perform a selection from the players table to determine the highest ID before creating any players, then we could just increment the ID from there. However, I want to account for concurrent access (even though we don't need this for the project), and I don't think finding the highest ID from the database will account for that.

**Comment by tompuglisi** [comment]
IDs are now being populated correctly using MySQL's auto-generation functionality. The names are now tracked on unique indexes and are set to be non-nullable, because we are assuming that they are unique.
